query AllMatches {
	matches{
    id
    date
    homePlayers{
      id
      name
      image
    }
    awayPlayers{
      id
      name
      image
    }
    referee{
      id
      name
    }
    stadium{
      id
      name
      city
      surface
    }
  }
}